# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '工具' do
pod 'SDWebImage', '~> 3.7.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.0.4'
pod 'MBProgressHUD', '~> 0.9.2'
end

target '工具Tests' do

end

target '工具UITests' do

end

